<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ3x3z9W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ3x3z9W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ3x3z9W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ3x3z9W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ3x3z9W\App_KernelDevDebugContainer([
    'container.build_hash' => 'J3x3z9W',
    'container.build_id' => '78e59798',
    'container.build_time' => 1701089587,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ3x3z9W');
