<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerADD0uOv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerADD0uOv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerADD0uOv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerADD0uOv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerADD0uOv\App_KernelDevDebugContainer([
    'container.build_hash' => 'ADD0uOv',
    'container.build_id' => '0e9626b7',
    'container.build_time' => 1701127689,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerADD0uOv');
