<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRRRa4cI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRRRa4cI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRRRa4cI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRRRa4cI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRRRa4cI\App_KernelDevDebugContainer([
    'container.build_hash' => 'RRRa4cI',
    'container.build_id' => '4860aeab',
    'container.build_time' => 1701090519,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRRRa4cI');
